import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import {
  ClerkProvider,
} from '@clerk/nextjs'


export const metadata: Metadata = {
  title: "Journey Through Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: {
  children: React.ReactNode;
  // Define the type for user
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <main className="bg-hookersgreen w-full min-h-screen">
            <Navbar />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
