import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import NextAuthProvider from "@/providers/NextAuthProvider";

export const metadata: Metadata = {
  title: "Journey Through Time",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
 
}: {
  children: React.ReactNode;
    // Define the type for user
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-hookersgreen min-h-screen">
          <NextAuthProvider>
            <Navbar/>
            {children}
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
